config/routes.rb
Rails.application.routes.draw do

  root "main_menu#index"

  resources :main_menu

  resources :products

    #get 'export_users' => 'exports#export_users', as: :export_users

  get 'progress_products/:job_id' => 'products#progress_job'

   get 'progress-job/:job_id' => 'progress_job/progress#show'

  get 'download_products' => 'products#download_csv', as: :download_csv

  post '/delete_all_products', to: 'products#delete_all_products', as: :delete_all_products

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]


end

app/models/depot.rb
class Depot < ActiveRecord::Base

	has_many :products

end

app/models/product.rb
class Product < ActiveRecord::Base

	belongs_to :depot

	def self.create_product
		10.times do 
			self.product_code = "Product"
			self.cost = 10
			self.owner = "owner1"
			self.save
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_menu_controller.rb
class MainMenuController < ApplicationController

	def index
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		products = Product.all
		@products = products.limit(10)
		@job = Delayed::Job.first
	end

	def new
		@product = Product.new
	end

	def progress_job
		begin
			@job = Delayed::Job.where(id: params[:job_id]).first
			
		  percentage = !@job.progress_max.zero? ? @job.progress_current / @job.progress_max.to_f * 100 : 0
		  render json: @job.attributes.merge!(percentage: percentage).to_json
		rescue
			render json: ''
		end
	end

	def create
		
		#Delayed::Job.enqueue ProductJob.new(product_params, action="creation"

		flash[:notice] = "We are creating your products"
		redirect_to root_path
	end

	def download_csv

		id = rand(1000)

		@job = Delayed::Job.enqueue ProductJob.new(id)
		#redirect_to root_path
	end




	private 

		def product_params
			params.require(:product).permit(:product_code, :cost, :owner, :depot_id)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_menu_helper.rb
module MainMenuHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/main_menu/index.html.erb
<h2>Index Page</h2>

<%= link_to "Products", products_path, class: 'btn btn-primary btn-xs' %>

app/views/products/download_csv.js.erb
//  alert('here')
<%# if @job.present? %>
	progress_job('<%= @job.try(:id) %>');
<%# end %>

app/views/products/index.html.erb
<div class="col-md-8">

	<%= link_to "Create Product", new_product_path, class: 'btn btn-primary btn-xs' %>

	<br>
	

	<br>

	<div class="export">
  <%= link_to 'Export Products', download_csv_path, remote: true, class: 'btn btn-primary btn-lg' %>
  <div class="well">
    <div class="row">
      <div class="col-xs-12">
        <div class="progress-status text-primary">
          0/0
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="progress progress-striped active">
          <div class="progress-bar">
            <div class="text-primary">
              0%
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'View csv', '/system/export.csv', class: 'btn btn-success export-link', style: 'display:none' %>
</div>


<%= link_to "Back", root_path, class: "btn btn-primary btn-xs" %>


</div> 	

<script>
    
  $(document).ready(function(){

    progress_job('<%= @job.try(:id) %>');

  })

</script>

app/views/products/new.html.erb
<%= link_to "Back", root_path, class: 'btn btn-primary btn-xs' %>
<br>

<%= form_for @product do |f| %>

	<div class="col-md-4"> 
		<%= f.label :product_code %>
		<%= f.text_field :product_code %>
		<br>

		<%= f.label :cost %>
		<%= f.text_field :cost %>
		<br>
		<%= f.label :owner %>
		<%= f.text_field :owner %>
		<br>

		<%= f.label :depot %>
		<%= f.text_field :depot_id, value: Depot.first.id %>
		<br>

		<%= f.submit %>

	</div>

<% end %>